
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
