services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./internal/migrations:/migrations
    working_dir: /migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "postgres://todo_user:secret@postgres:5432/todo_db?sslmode=disable" ]
    command: [ "up" ]
    depends_on:
      - postgres

volumes:
  postgres_data:

